export const MOBILE_HTML = String.raw`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#234b40"><meta name="apple-mobile-web-app-capable" content="yes"><title>LingoLeaf · 随身复习</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f7f6f1;color:#243b33;font:15px/1.7 system-ui,-apple-system,'Segoe UI',sans-serif}header{background:#234b40;color:#fff;padding:24px max(24px,calc((100vw - 740px)/2));display:flex;align-items:center;justify-content:space-between}.logo{font:26px Georgia,serif;letter-spacing:-1px}.label{font-size:12px;opacity:.7}main{max-width:740px;margin:auto;padding:28px 20px 60px}h1{font-size:29px;letter-spacing:-1px;margin:0}p{color:#6d7e72}.tabs{display:flex;gap:8px;margin:26px 0}button{border:0;border-radius:12px;padding:12px 18px;background:#e8ece5;color:#234b40;font:inherit;cursor:pointer}button.active,.primary{background:#234b40;color:white}button:focus-visible,input:focus-visible{outline:3px solid #deaa69;outline-offset:3px}.card{background:white;border:1px solid #e3e7de;padding:26px;border-radius:22px;margin:16px 0;box-shadow:0 8px 36px #243b3305}.sentence{font:25px/1.5 Georgia,'Microsoft YaHei',serif;overflow-wrap:anywhere;white-space:pre-wrap}.eyebrow{font-size:11px;letter-spacing:2px;color:#7b887e;text-transform:uppercase}.corrected{border-left:3px solid #82a68b;padding-left:18px}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.ratings button{flex:1;min-width:65px;padding:12px 9px}.muted{color:#7b887e;font-size:13px}.error{padding:16px;background:#fff1e9;border-radius:12px;color:#8b4024;white-space:pre-wrap}input{width:100%;border:1px solid #d9e0d6;padding:14px;border-radius:12px;background:white;font:inherit}mark{background:#fff0d6;color:inherit;padding:2px 5px}.tag{display:inline-block;background:#edf2eb;color:#607c67;padding:3px 10px;border-radius:8px;font-size:12px}.hidden{display:none}.full{width:100%;margin-top:20px}hr{border:0;border-top:1px solid #edf0e9;margin:22px 0}.empty{text-align:center;padding:30px 5px}#status{font-size:12px;color:#b4cbbc}.issue{border-top:1px solid #edf0e9;padding:15px 0}.toast{position:sticky;bottom:12px;background:#234b40;color:white;padding:12px 18px;border-radius:12px}</style></head>
<body><header><div><div class="logo">❧ LingoLeaf</div><div class="label">每一句，都有新收获</div></div><span id="status">正在连接</span></header><main><div class="eyebrow">YOUR POCKET PRACTICE</div><h1>让进步，发生在今天。</h1><p id="summary">正在读取你的学习库…</p><div class="tabs"><button id="reviewTab" class="active">今日复习</button><button id="libraryTab">句子收藏</button><button id="refresh" aria-label="刷新学习库">↻</button></div><div id="error" class="hidden error" role="alert"></div><section id="review"></section><section id="library" class="hidden"><input id="search" aria-label="搜索句子" placeholder="搜索句子、语法规则…"><div id="items"></div></section><p class="muted">学习进度会自动保存到桌面。请保持 LingoLeaf 运行，并连接同一可信网络。电脑关机后可在同步目录中阅读 Markdown 笔记。</p><div id="toast" class="hidden toast" role="status"></div></main>
<script>
let token=location.hash.slice(1);try{token=token||sessionStorage.getItem('lingoleafToken')||'';if(token)sessionStorage.setItem('lingoleafToken',token)}catch{}if(token)history.replaceState(null,'',location.pathname);
let entries=[],revealedId=null,currentId=null,tab='review',busy=false,refreshing=false,clockOffset=0,toastTimer;
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function syncControls(){$('refresh').disabled=busy||refreshing;document.querySelectorAll('[data-rating],#reveal').forEach(b=>b.disabled=busy||refreshing)}
function syncClock(now){const value=Date.parse(now);if(Number.isFinite(value))clockOffset=value-Date.now()}
async function request(path,body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal});const data=await r.json();if(!r.ok)throw Error(data.error||'连接失败');return data}catch(e){if(controller.signal.aborted)throw Error(body?'未收到保存结果，请刷新确认复习状态后再操作。':'连接超时，请检查电脑是否运行并连接同一网络。');throw e}finally{clearTimeout(timer)}}
async function refresh(){if(busy||refreshing)return;refreshing=true;syncControls();try{const data=await request('/api/entries');entries=data.entries;syncClock(data.now);$('error').classList.add('hidden');$('status').textContent='● 已连接桌面';render()}catch(e){$('error').textContent=e.message;$('error').classList.remove('hidden');$('status').textContent='连接已断开';if(!entries.length)$('summary').textContent='请在桌面打开「手机同步」，重新扫描二维码。'}finally{refreshing=false;syncControls()}}
function due(){const now=Date.now()+clockOffset;return entries.filter(e=>Date.parse(e.review.dueAt)<=now).sort((a,b)=>a.review.dueAt.localeCompare(b.review.dueAt))}
function answer(e){return '<div class="corrected"><div class="eyebrow">'+(e.mode==='grammar'?'CORRECTION':'TRANSLATION')+'</div><div class="sentence">'+esc(e.corrected)+'</div></div><p>'+esc(e.explanation)+'</p>'+e.issues.map(i=>'<div class="issue"><span class="tag">'+esc(i.kind==='grammar'?'语法':'表达建议')+' · '+esc(i.rule)+'</span><p><mark>'+esc(i.original)+'</mark> → '+esc(i.replacement)+'</p>'+esc(i.explanation)+'</div>').join('')+(e.example?'<hr><div class="eyebrow">TRY ANOTHER SENTENCE</div><p>'+esc(e.example)+'</p>':'')}
function render(includeItems=true){const queue=due();$('summary').textContent=entries.length+' 个句子已收藏 · '+queue.length+' 个等待复习';const e=queue.find(item=>item.id===currentId)||queue[0];currentId=e?.id||null;$('review').innerHTML=e?'<article class="card"><div class="row"><span class="tag">'+(e.mode==='grammar'?'找出语法问题':'试着翻译')+'</span><span class="muted">还剩 '+queue.length+' 句</span></div><p class="sentence">'+esc(e.original)+'</p><p class="muted">先想一想，再揭晓答案。</p>'+(revealedId===e.id?'<hr>'+answer(e)+'<hr><div class="ratings row"><button data-rating="again">再学一次</button><button data-rating="hard">有点难</button><button data-rating="good">记住了</button><button data-rating="easy">很轻松</button></div>':'<button class="primary full" id="reveal">查看答案</button>')+'</article>':'<article class="card empty"><div class="sentence">'+(entries.length?'今日复习完成 ☀':'从第一句话开始。')+'</div><p>'+(entries.length?'新句子和到期复习会出现在这里。':'在电脑选中一句话，按快捷键纠错或翻译，然后在这里继续学习。')+'</p></article>';
if($('reveal'))$('reveal').onclick=()=>{if(busy||refreshing)return;revealedId=e.id;render(false)};document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>rate(e.id,b.dataset.rating));if(includeItems)renderItems();syncControls()}
function renderItems(){const q=$('search').value.toLowerCase();const list=entries.filter(e=>(e.original+' '+e.corrected+' '+e.tags.join(' ')+' '+e.issues.map(i=>i.rule).join(' ')).toLowerCase().includes(q));$('items').innerHTML=list.length?list.map(e=>'<details class="card"><summary class="sentence">'+esc(e.original)+'</summary><hr>'+answer(e)+'</details>').join(''):'<p class="empty muted">没有找到句子。</p>'}
async function rate(id,rating){if(busy||refreshing)return;busy=true;syncControls();try{const data=await request('/api/review',{id,rating});entries=entries.map(e=>e.id===id?data.entry:e);syncClock(data.now);currentId=null;revealedId=null;$('error').classList.add('hidden');$('status').textContent='● 已连接桌面';render();$('toast').textContent='复习进度已保存到桌面';$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),2200)}catch(e){$('error').textContent=e.message;$('error').classList.remove('hidden')}finally{busy=false;syncControls()}}
function switchTab(next){tab=next;$('review').classList.toggle('hidden',tab!=='review');$('library').classList.toggle('hidden',tab!=='library');$('reviewTab').classList.toggle('active',tab==='review');$('libraryTab').classList.toggle('active',tab==='library');if(tab==='review'&&!busy&&!refreshing)render(false)}
$('reviewTab').onclick=()=>switchTab('review');$('libraryTab').onclick=()=>switchTab('library');$('refresh').onclick=refresh;$('search').oninput=renderItems;document.addEventListener('visibilitychange',()=>{if(!document.hidden)void refresh()});setInterval(()=>{if(!document.hidden&&!busy&&!refreshing)render(false)},15000);refresh();
</script></body></html>`;
